name: Basic CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "hello world"
  
  hi:
    runs-on:
      - codebuild-ds-${{ github.run_id }}-${{ github.run_attempt }}
    env:
      ENV_VAR: "some value"
      RANDOM: "${{ github.run_id }}"
    steps:
      - run: echo "Hello World! hi!"
  
  konnichiwa:
    runs-on:
      - codebuild-hostrunner-prod-${{ github.run_id }}-${{ github.run_attempt }}
    env:
      ENV_VAR: "some value"
      RANDOM: "${{ github.run_id }}"
    steps:
      - run: echo "Hello World! konnichiwa!"
